apiVersion: k8s.streamnative.io/v1alpha1
kind: PulsarCoordinator
metadata:
  name: private-cloud
  namespace: pulsar
spec:
  image: streamnative/private-cloud:3.1.1.1
---
apiVersion: zookeeper.streamnative.io/v1alpha1
kind: ZooKeeperCluster
metadata:
  name: private-cloud
  namespace: pulsar
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  image: streamnative/private-cloud:3.1.1.1
  replicas: 3
  pod:
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
    jvmOptions:
      memoryOptions:
        - >
          -XX:MaxRAMPercentage=85
          -XX:+AlwaysPreTouch
      gcOptions:
        - >
          -XX:+UseZGC
          -Djute.maxbuffer=10485760
          -Dzookeeper.forceSync=no
          -XX:-ZUncommit
      gcLoggingOptions:
        - >
          -Xlog:gc*:file=/tmp/zk_gc.log::filecount=5,filesize=5m
      extraOptions:
        - >
          -XX:CompileThreshold=2000
    securityContext:
      runAsNonRoot: true
  persistence:
    data:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 40Gi
      storageClassName: ssd-raid
    dataLog:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: nvme-raid
    reclaimPolicy: Delete
---
apiVersion: bookkeeper.streamnative.io/v1alpha1
kind: BookKeeperCluster
metadata:
  name: private-cloud
  namespace: pulsar
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  image: streamnative/private-cloud:3.1.1.1
  replicas: 3
  zkServers: private-cloud-zk:2181
  pod:
    resources:
      requests:
        cpu: 2
        memory: 8Gi
      limits:
        cpu: 3
        memory: 12Gi
    jvmOptions:
      memoryOptions:
        - >
          -XX:MaxRAMPercentage=45
          -XX:+AlwaysPreTouch
      gcOptions:
        - >
          -XX:+UseZGC
          -Djute.maxbuffer=10485760
          -Dzookeeper.forceSync=no
          -XX:-ZUncommit
      gcLoggingOptions:
        - >
          -Xlog:gc*:file=/tmp/bk_gc.log::filecount=5,filesize=5m
      extraOptions:
        - >
          -XX:CompileThreshold=2000
    securityContext:
      runAsNonRoot: true
  storage:
    journal:
      numDirsPerVolume: 1
      numVolumes: 1
      volumeClaimTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: nvme-raid
    ledger:
      numDirsPerVolume: 1
      numVolumes: 1
      volumeClaimTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: ssd-raid
    reclaimPolicy: Delete
  autoRecovery:
    replicas: 1
    pod:
      annotations:
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
---
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarBroker
metadata:
  name: private-cloud
  namespace: pulsar
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  image: streamnative/private-cloud:3.1.1.1
  replicas: 3
  zkServers: private-cloud-zk:2181
  config:
    clusterName: private-cloud
  pod:
    resources:
      requests:
        cpu: 2
        memory: 8Gi
      limits:
        cpu: 3
        memory: 12Gi
    jvmOptions:
      memoryOptions:
        - >
          -XX:MaxRAMPercentage=45
          -XX:+AlwaysPreTouch
      gcOptions:
        - >
          -XX:+UseZGC
          -Djute.maxbuffer=10485760
          -Dzookeeper.forceSync=no
          -XX:-ZUncommit
          -XX:+UseNUMA
      gcLoggingOptions:
        - >
          -Xlog:gc*:file=/tmp/br_gc.log::filecount=5,filesize=5m
      extraOptions:
        - >
          -XX:CompileThreshold=2000
    securityContext:
      runAsNonRoot: true

---
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarProxy
metadata:
  name: private-cloud
  namespace: pulsar
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  image: streamnative/private-cloud:3.1.1.1
  replicas: 1
  brokerAddress: private-cloud-broker
  pod:
    resources:
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        cpu: 2
        memory: 8Gi
    jvmOptions:
      memoryOptions:
        - >
          -XX:MaxRAMPercentage=45
          -XX:+AlwaysPreTouch
      gcOptions:
        - >
          -XX:+UseZGC
          -Djute.maxbuffer=10485760
          -Dzookeeper.forceSync=no
          -XX:-ZUncommit
      gcLoggingOptions:
        - >
          -Xlog:gc*:file=/tmp/px_gc.log::filecount=5,filesize=5m
      extraOptions:
        - >
          -XX:CompileThreshold=2000
    securityContext:
      runAsNonRoot: true
---
apiVersion: k8s.streamnative.io/v1alpha1
kind: Console
metadata:
  name: private-cloud
  namespace: pulsar
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
  labels:
    k8s.streamnative.io/coordinator-name: private-cloud
spec:
  image: streamnative/private-cloud-console:v2.3.4
  webServiceUrl: http://private-cloud-broker:8080
