apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-io1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"  # Specify the IOPS per GB, or you can use 'iops' to set a specific IOPS value
  fsType: ext4      # Filesystem type (ext4, xfs, etc.)
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

